import { supabase } from './supabase-client.js?v=20260913-loyalty';
import QRCode from 'https://cdn.jsdelivr.net/npm/qrcode@1.5.4/+esm';
const {data:{session}}=await supabase.auth.getSession();
if(!session){location.replace('login.html');throw new Error('Sesión requerida');}
const {data:me}=await supabase.from('profiles').select('role').eq('id',session.user.id).single();
if(me?.role!=='admin'){location.replace('membresia.html');throw new Error('Acceso de administrador requerido');}
let profiles=[],cards=[];await loadData();
async function loadData(){const [p,c]=await Promise.all([supabase.from('profiles').select('id,full_name,email,role').order('full_name'),supabase.from('loyalty_cards').select('id,user_id,card_number,tier_code,status,points_balance,expires_at').order('issued_at',{ascending:false})]);profiles=(p.data||[]).filter(x=>x.role==='customer');cards=c.data||[];const issued=new Set(cards.map(x=>x.user_id));document.getElementById('clientSelect').innerHTML='<option value="">Seleccionar…</option>'+profiles.filter(x=>!issued.has(x.id)).map(x=>`<option value="${x.id}">${escapeHtml(x.full_name||x.email)}</option>`).join('');const map=new Map(profiles.map(x=>[x.id,x]));document.getElementById('cardsBody').innerHTML=cards.length?cards.map(card=>`<tr><td>${escapeHtml(map.get(card.user_id)?.full_name||map.get(card.user_id)?.email||'Cliente')}</td><td>${formatCard(card.card_number)}</td><td>${labelTier(card.tier_code)}</td><td>${card.points_balance}</td><td>${escapeHtml(card.status)}</td><td><div class="actions"><button class="secondary small" data-points="${card.id}">Puntos</button><button class="secondary small" data-rotate="${card.id}">Nuevo QR</button></div></td></tr>`).join(''):'<tr><td colspan="6">Aún no hay tarjetas emitidas.</td></tr>';bindActions();}
document.getElementById('issueForm').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget,status=document.getElementById('issueStatus'),f=new FormData(form);status.textContent='Emitiendo…';status.className='status';const result=await adminAction({action:'issue_card',user_id:f.get('user_id'),tier_code:f.get('tier_code'),expires_at:f.get('expires_at')?new Date(`${f.get('expires_at')}T23:59:59`).toISOString():null});if(result.error){status.className='status error';status.textContent=result.error;return}status.className='status ok';status.textContent='Tarjeta emitida correctamente.';await showQr(result.validation_url);form.reset();await loadData();});
function bindActions(){document.querySelectorAll('[data-points]').forEach(button=>button.addEventListener('click',async()=>{const amount=prompt('Puntos a agregar. Usa un número negativo para descontar:');if(amount===null)return;const points=Number(amount);const description=prompt('Concepto del movimiento:','Ajuste administrativo')||'Ajuste administrativo';const result=await adminAction({action:'add_points',card_id:button.dataset.points,points,event_type:points>=0?'earn':'adjust',description});alert(result.error||`Saldo actualizado: ${result.balance.points_balance} puntos`);await loadData();}));document.querySelectorAll('[data-rotate]').forEach(button=>button.addEventListener('click',async()=>{if(!confirm('El QR anterior dejará de funcionar. ¿Continuar?'))return;const result=await adminAction({action:'rotate_qr',card_id:button.dataset.rotate});if(result.error){alert(result.error);return}await showQr(result.validation_url);window.scrollTo({top:0,behavior:'smooth'});}));}
async function adminAction(payload){const response=await fetch('https://mtpqpxcmngrsivntbgcc.supabase.co/functions/v1/loyalty-admin',{method:'POST',headers:{Authorization:`Bearer ${session.access_token}`,apikey:'sb_publishable_5Dan5EdjEHyfPDG30opQ8Q_d-Kkp72_','Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();return response.ok?data:{error:data.error||'No fue posible completar la operación.'};}
async function showQr(url){const result=document.getElementById('qrResult');result.hidden=false;document.getElementById('qrUrl').value=url;await QRCode.toCanvas(document.getElementById('adminQr'),url,{width:230,margin:2,errorCorrectionLevel:'M'});}
document.getElementById('copyQr').addEventListener('click',()=>navigator.clipboard.writeText(document.getElementById('qrUrl').value));document.getElementById('logoutBtn').addEventListener('click',async()=>{await supabase.auth.signOut();location.replace('login.html');});
function labelTier(v){return({azul:'RHO Azul',black:'RHO Black',oro:'RHO Oro',platino:'RHO Platino'})[v]||v}function formatCard(v){return String(v).replace(/(.{4})/g,'$1 ').trim()}function escapeHtml(value){return String(value).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
