create table if not exists public.loyalty_admin_audit (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references public.profiles(id),
  action text not null check (action in ('issue_card','rotate_qr','add_points')),
  card_id uuid references public.loyalty_cards(id) on delete set null,
  target_user_id uuid references public.profiles(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb check (jsonb_typeof(metadata) = 'object'),
  created_at timestamptz not null default now()
);

comment on table public.loyalty_admin_audit is
  'Append-only audit trail for privileged loyalty actions. Readable only by administrators.';

create index if not exists loyalty_admin_audit_admin_date_idx
  on public.loyalty_admin_audit (admin_user_id, created_at desc);
create index if not exists loyalty_admin_audit_card_date_idx
  on public.loyalty_admin_audit (card_id, created_at desc)
  where card_id is not null;
create index if not exists loyalty_admin_audit_target_date_idx
  on public.loyalty_admin_audit (target_user_id, created_at desc)
  where target_user_id is not null;

alter table public.loyalty_admin_audit enable row level security;

drop policy if exists loyalty_admin_audit_select on public.loyalty_admin_audit;
create policy loyalty_admin_audit_select
on public.loyalty_admin_audit
for select
to authenticated
using ((select private.is_admin()));

revoke all on table public.profiles from anon, authenticated;
grant select, update on table public.profiles to authenticated;

revoke all on table public.site_visits from anon, authenticated;
grant insert on table public.site_visits to anon, authenticated;
grant select on table public.site_visits to authenticated;

revoke all on table public.marketing_campaigns from anon, authenticated;
grant select, insert, update, delete on table public.marketing_campaigns to authenticated;

revoke all on table public.campaign_recipients from anon, authenticated;
grant select, insert, update, delete on table public.campaign_recipients to authenticated;

revoke all on table public.loyalty_tiers from anon, authenticated;
grant select on table public.loyalty_tiers to anon;
grant select, insert, update, delete on table public.loyalty_tiers to authenticated;

revoke all on table public.loyalty_customer_details from anon, authenticated;
grant select, insert, update, delete on table public.loyalty_customer_details to authenticated;

revoke all on table public.loyalty_cards from anon, authenticated;
grant select on table public.loyalty_cards to authenticated;

revoke all on table public.loyalty_qr_tokens from anon, authenticated;

revoke all on table public.loyalty_points_ledger from anon, authenticated;
grant select on table public.loyalty_points_ledger to authenticated;

revoke all on table public.loyalty_transactions from anon, authenticated;
grant select on table public.loyalty_transactions to authenticated;

revoke all on table public.loyalty_transaction_items from anon, authenticated;
grant select on table public.loyalty_transaction_items to authenticated;

revoke all on table public.loyalty_rewards from anon, authenticated;
grant select, insert, update, delete on table public.loyalty_rewards to authenticated;

revoke all on table public.loyalty_redemptions from anon, authenticated;
grant select on table public.loyalty_redemptions to authenticated;

revoke all on table public.loyalty_qr_scans from anon, authenticated;
grant select on table public.loyalty_qr_scans to authenticated;

revoke all on table public.loyalty_admin_audit from anon, authenticated;
grant select on table public.loyalty_admin_audit to authenticated;
